name: integration
on:
  push:
    paths:
      - "src/**/*"
      - "package.json"
jobs:
  lint:
    name: Lint source files
    runs-on: ubuntu-latest
  coverage:
    name: Testing Suite
    needs: lint
    runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v1

        - name: Install dependencies
          uses: Adzz/jest_test_action@v1.0.0
          with:
            command: install
        - name: Run Testing Suite
          uses: Adzz/jest_test_action@v1.0.0
          with:
            command: test
        - name: Upload Coverage Report
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build from source
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          command: install
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          command: build:check

